version: "3.8"

services:
  db:
    container_name: senspozitiv-db
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - "5454:5432"
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}


  redis:
    image: redis:alpine
    networks:
      - internal
    container_name: senspozitiv-redis
    expose:
      - "6379"

  sens_pozitiv:
    container_name: senspozitiv-admin
    build:
      context: ./sens_pozitiv
    command: dockerize -wait tcp://db:5432 -timeout 90s
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./sens_pozitiv:/code
    ports:
      - "8070:8070"
    depends_on:
      - db
      - redis

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    name: senspozitiv-pgdata
