# Generated by Django 3.2.12 on 2022-03-30 10:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('patient_request', 'Patient Request Form')], max_length=50, verbose_name='Template')),
                ('text_content', models.TextField(verbose_name='Text content')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, verbose_name='HTML content')),
                ('lang', models.CharField(choices=[('ro', 'Romanian'), ('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'unique_together': {('template', 'lang')},
            },
        ),
    ]
