# Generated by Django 3.2.12 on 2022-03-30 10:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medical Center Name')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255, verbose_name='Medication Name')),
                ('medication_quantity', models.CharField(blank=True, max_length=255, verbose_name='Medication Quantity')),
                ('medication_details', models.TextField(blank=True, verbose_name='Medication Details')),
                ('med_service_type', models.CharField(max_length=255, verbose_name='Medical Service Type')),
                ('med_service_quantity', models.CharField(blank=True, max_length=255, verbose_name='Medical Service Quantity')),
                ('med_service_details', models.TextField(blank=True, verbose_name='Medical Service Details')),
                ('other_service_type', models.CharField(max_length=255, verbose_name='Non-Medical Service Type')),
                ('other_service_quantity', models.CharField(blank=True, max_length=255, verbose_name='Non-Medical Service Quantity')),
                ('other_service_details', models.TextField(blank=True, verbose_name='Non-Medical Service Details')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.clinic')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Contact Person Role')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Person Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='e.g. +40723000123', max_length=128, region=None, verbose_name='Contact Person Phone Number')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.clinic')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='e.g. +40723000123', max_length=128, region=None, verbose_name='Phone Number')),
                ('treatment_schema', models.TextField(verbose_name='Treatment Schema')),
                ('available_treatment', models.CharField(help_text='For how long do you have treatment available?', max_length=100, verbose_name='Treatment Schema')),
                ('cd4_amount', models.CharField(help_text='CD4 at last check', max_length=100, verbose_name='CD4 Amount')),
                ('viral_load', models.CharField(help_text='Last measured viral load', max_length=100, verbose_name='Viral Load')),
                ('other_affections', models.TextField(help_text='Other affections or life conditions', verbose_name='Other Affections')),
                ('medical_urgencies', models.TextField(help_text='Medical urgencies related to HIV or other', verbose_name='Medical Urgencies')),
                ('route', models.CharField(choices=[('ROM', 'Stays in Romania'), ('TRA', 'In Transit'), ('UNK', 'Unsure')], default='ROM', max_length=3, verbose_name='Route')),
                ('location', models.CharField(choices=[('RO', 'Romania'), ('UA', 'Ukraine'), ('MD', 'Moldavia'), ('OTH', 'Other')], default='RO', max_length=3, verbose_name='Current Location')),
                ('location_details', models.TextField(blank=True, help_text='County, Town and other relevant details', verbose_name='Current Location Details')),
                ('other_details', models.TextField(blank=True, verbose_name='Other Details')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.clinic')),
            ],
            options={
                'verbose_name': 'Patient Request',
                'verbose_name_plural': 'Patient Requests',
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
    ]
