# Generated by Django 3.2.12 on 2022-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='available_treatment',
            field=models.CharField(help_text='For how long do you have treatment available?', max_length=100, verbose_name='Available Schema'),
        ),
    ]
